# Generated by Django 2.1.1 on 2018-09-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('type', models.CharField(default='', max_length=200)),
                ('density', models.FloatField(default=0)),
                ('area', models.FloatField(default=0)),
                ('kindergarten', models.IntegerField(default=0)),
                ('primary_school', models.IntegerField(default=0)),
                ('secondary_school', models.IntegerField(default=0)),
                ('p12_school', models.IntegerField(default=0)),
                ('other_school', models.IntegerField(default=0)),
                ('born_overseas', models.FloatField(default=0)),
                ('except_eng', models.FloatField(default=0)),
                ('culture_group1_name', models.CharField(default='', max_length=250)),
                ('culture_group2_name', models.CharField(default='', max_length=250)),
                ('culture_group3_name', models.CharField(default='', max_length=250)),
                ('culture_group4_name', models.CharField(default='', max_length=250)),
                ('culture_group1_per', models.FloatField(default=0)),
                ('culture_group2_per', models.FloatField(default=0)),
                ('culture_group3_per', models.FloatField(default=0)),
                ('culture_group4_per', models.FloatField(default=0)),
                ('child_protection', models.IntegerField(default=0)),
                ('community_health', models.IntegerField(default=0)),
                ('homeless', models.IntegerField(default=0)),
                ('disability', models.IntegerField(default=0)),
                ('mental_health', models.IntegerField(default=0)),
                ('human', models.IntegerField(default=0)),
                ('dental', models.IntegerField(default=0)),
                ('general_practice', models.IntegerField(default=0)),
                ('pharmacy', models.IntegerField(default=0)),
                ('allied_health', models.IntegerField(default=0)),
                ('complementary_health', models.IntegerField(default=0)),
                ('residential_aged_care', models.IntegerField(default=0)),
                ('licensed_aged_care', models.IntegerField(default=0)),
                ('nearest_health', models.CharField(default='', max_length=250)),
                ('dis_nearest_health', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=50)),
                ('street_number', models.CharField(default='', max_length=50)),
                ('road_name', models.CharField(default='', max_length=200)),
                ('road_type', models.CharField(default='', max_length=200)),
                ('suburb', models.CharField(default='', max_length=200)),
                ('postcode', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('sub_location', models.CharField(default='', max_length=200)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=50)),
                ('address_line', models.CharField(default='', max_length=200)),
                ('address_town', models.CharField(default='', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('contact', models.CharField(default='', max_length=50)),
                ('education_sector', models.CharField(default='', max_length=50)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Suburblocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Language'),
        ),
    ]
