# Generated by Django 2.1.1 on 2018-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=50)),
                ('address_line', models.CharField(default='', max_length=200)),
                ('address_town', models.CharField(default='', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('contact', models.CharField(default='', max_length=50)),
                ('education_sector', models.CharField(default='', max_length=50)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
    ]
